all: 
	cd module-01 && $(MAKE)
	cd module-02 && $(MAKE)
	cd module-03 && $(MAKE)
	cd module-04 && $(MAKE)
	cd module-05 && $(MAKE)
	cd module-06 && $(MAKE)
	cd module-07 && $(MAKE)
	cd module-08 && $(MAKE)
